// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Concepts',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Clinical',
          key: 'clinical-concepts',
          items: ['concepts/clinical/patient'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Flows',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'flows'}],
    },
    {
      type: 'category',
      label: 'References',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Clinical',
          key: 'clinical-references',
          items: ['references/clinical/patient'],
        },
      ],
    },
  ],
};

export default sidebars;
